version: "3.8"
services:

  configserver:
    image: fabrix1987/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - fabrix1987
   
  eurekaserver:
    image: fabrix1987/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - fabrix1987
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      
  flights:
    image: fabrix1987/flights:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - fabrix1987
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: flights
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      
  flights1:
    image: fabrix1987/flights:latest
    mem_limit: 700m
    ports:
      - "8081:8080"
    networks:
      - fabrix1987
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: flights
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/      
  
  hotels:
    image: fabrix1987/hotels:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - fabrix1987
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: hotels
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      
  gatewayserver:
    image: fabrix1987/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - fabrix1987
    depends_on:
      - configserver
      - eurekaserver
      - flights
      - hotels
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/          
      
networks:
  fabrix1987:  